# Official documentation at http://goreleaser.com
project_name: argo-wf-atomic
builds:
- env:
  - CGO_ENABLED=0
  binary: argo-wf-atomic
  goarch:
    - amd64
    - arm64
  goos:
    - windows
    - linux
    - darwin
  ldflags:
    - -X github.com/linuxsuren/cgit/app.version={{.Version}}
    - -X github.com/linuxsuren/cgit/app.commit={{.ShortCommit}}
    - -X github.com/linuxsuren/cgit/app.date={{.Date}}
    - -w
dist: release
archives:
- name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"
  format_overrides:
    - goos: windows
      format: zip
  files:
    - README.md
snapshot:
  name_template: "{{ .Tag }}-next-{{.ShortCommit}}"
